# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "50055:50055"
    env_file:
      - .env
    restart: always
    depends_on:
      eventstore.db:
        condition: service_healthy
      mongodb:
        condition: service_started
      sso:
        condition: service_started

  sso:
    image: sso-server-app
    ports:
      - "50051:50051"
    depends_on:
      eventstore.db:
        condition: service_healthy
      mongodb:
        condition: service_started

  eventstore.db:
    image: eventstore/eventstore:24.2.0-jammy
    environment:
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2113/health/live"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - type: volume
        source: mongodb-volume-data
        target: /var/lib/mongodb
    
volumes:
  mongodb-volume-data:
  eventstore-volume-data:
  eventstore-volume-logs: