# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "50055:50055"
    env_file:
      - .env
    restart: always
    depends_on:
      - nats  
      - mongodb

  nats:
    image: nats:latest
    ports:
      - "4240:4222"
    volumes:
      - ./nats-config.conf:/etc/nats/nats-config.conf
    entrypoint: ["nats-server", "-c", "/etc/nats/nats-config.conf"]

  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password
    ports:
      - "27037:27017"
    volumes:
      - type: volume
        source: mongodb-volume-data
        target: /var/lib/mongodb

volumes:
  mongodb-volume-data:

