version: '3.9'

services:

  app:
    build:
      context: .
      dockerfile: ./Dockerfile.yaml
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    restart: always

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    entrypoint: ["nats-server"]