services:

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    entrypoint: ["nats-server"]

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NATS_URL=nats://nats:4222
    restart: always
    depends_on:
      - nats  