// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: proto/resume.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Skill string `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
}

func (x *Skill) Reset() {
	*x = Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Skill) ProtoMessage() {}

func (x *Skill) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Skill.ProtoReflect.Descriptor instead.
func (*Skill) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{0}
}

func (x *Skill) GetSkill() string {
	if x != nil {
		return x.Skill
	}
	return ""
}

type ResumeCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Education     string   `protobuf:"bytes,1,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe       string   `protobuf:"bytes,2,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
	Skills        []*Skill `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	BirthDate     string   `protobuf:"bytes,4,opt,name=birthDate,proto3" json:"birthDate,omitempty"` // YYYY-MM-DD пример: 1990-05-15
	Direction     string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	AboutProjects string   `protobuf:"bytes,6,opt,name=aboutProjects,proto3" json:"aboutProjects,omitempty"`
	Portfolio     string   `protobuf:"bytes,7,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *ResumeCreated) Reset() {
	*x = ResumeCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeCreated) ProtoMessage() {}

func (x *ResumeCreated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeCreated.ProtoReflect.Descriptor instead.
func (*ResumeCreated) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{1}
}

func (x *ResumeCreated) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ResumeCreated) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

func (x *ResumeCreated) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeCreated) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ResumeCreated) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ResumeCreated) GetAboutProjects() string {
	if x != nil {
		return x.AboutProjects
	}
	return ""
}

func (x *ResumeCreated) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type ResumeChanged struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeId      string   `protobuf:"bytes,1,opt,name=resumeId,proto3" json:"resumeId,omitempty"`
	Education     string   `protobuf:"bytes,2,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe       string   `protobuf:"bytes,3,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
	Skills        []*Skill `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	BirthDate     string   `protobuf:"bytes,5,opt,name=birthDate,proto3" json:"birthDate,omitempty"` // YYYY-MM-DD пример: 1990-05-15
	Direction     string   `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	AboutProjects string   `protobuf:"bytes,7,opt,name=aboutProjects,proto3" json:"aboutProjects,omitempty"`
	Portfolio     string   `protobuf:"bytes,8,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *ResumeChanged) Reset() {
	*x = ResumeChanged{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResumeChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeChanged) ProtoMessage() {}

func (x *ResumeChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeChanged.ProtoReflect.Descriptor instead.
func (*ResumeChanged) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{2}
}

func (x *ResumeChanged) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *ResumeChanged) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ResumeChanged) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

func (x *ResumeChanged) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ResumeChanged) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ResumeChanged) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ResumeChanged) GetAboutProjects() string {
	if x != nil {
		return x.AboutProjects
	}
	return ""
}

func (x *ResumeChanged) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type CreateResumeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Education     string   `protobuf:"bytes,1,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe       string   `protobuf:"bytes,2,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
	Skills        []*Skill `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	BirthDate     string   `protobuf:"bytes,4,opt,name=birthDate,proto3" json:"birthDate,omitempty"` // YYYY-MM-DD пример: 1990-05-15
	Direction     string   `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"`
	AboutProjects string   `protobuf:"bytes,6,opt,name=aboutProjects,proto3" json:"aboutProjects,omitempty"`
	Portfolio     string   `protobuf:"bytes,7,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *CreateResumeReq) Reset() {
	*x = CreateResumeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeReq) ProtoMessage() {}

func (x *CreateResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeReq.ProtoReflect.Descriptor instead.
func (*CreateResumeReq) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{3}
}

func (x *CreateResumeReq) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *CreateResumeReq) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

func (x *CreateResumeReq) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateResumeReq) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateResumeReq) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *CreateResumeReq) GetAboutProjects() string {
	if x != nil {
		return x.AboutProjects
	}
	return ""
}

func (x *CreateResumeReq) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type CreateResumeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateResumeRes) Reset() {
	*x = CreateResumeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResumeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResumeRes) ProtoMessage() {}

func (x *CreateResumeRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResumeRes.ProtoReflect.Descriptor instead.
func (*CreateResumeRes) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{4}
}

type ChangeResumeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResumeId      string   `protobuf:"bytes,1,opt,name=resumeId,proto3" json:"resumeId,omitempty"`
	Education     string   `protobuf:"bytes,2,opt,name=education,proto3" json:"education,omitempty"`
	AboutMe       string   `protobuf:"bytes,3,opt,name=aboutMe,proto3" json:"aboutMe,omitempty"`
	Skills        []*Skill `protobuf:"bytes,4,rep,name=skills,proto3" json:"skills,omitempty"`
	BirthDate     string   `protobuf:"bytes,5,opt,name=birthDate,proto3" json:"birthDate,omitempty"` // YYYY-MM-DD пример: 1990-05-15
	Direction     string   `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	AboutProjects string   `protobuf:"bytes,7,opt,name=aboutProjects,proto3" json:"aboutProjects,omitempty"`
	Portfolio     string   `protobuf:"bytes,8,opt,name=portfolio,proto3" json:"portfolio,omitempty"`
}

func (x *ChangeResumeReq) Reset() {
	*x = ChangeResumeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeResumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeResumeReq) ProtoMessage() {}

func (x *ChangeResumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeResumeReq.ProtoReflect.Descriptor instead.
func (*ChangeResumeReq) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeResumeReq) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *ChangeResumeReq) GetEducation() string {
	if x != nil {
		return x.Education
	}
	return ""
}

func (x *ChangeResumeReq) GetAboutMe() string {
	if x != nil {
		return x.AboutMe
	}
	return ""
}

func (x *ChangeResumeReq) GetSkills() []*Skill {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ChangeResumeReq) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *ChangeResumeReq) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *ChangeResumeReq) GetAboutProjects() string {
	if x != nil {
		return x.AboutProjects
	}
	return ""
}

func (x *ChangeResumeReq) GetPortfolio() string {
	if x != nil {
		return x.Portfolio
	}
	return ""
}

type ChangeResumeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ChangeResumeRes) Reset() {
	*x = ChangeResumeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_resume_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeResumeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeResumeRes) ProtoMessage() {}

func (x *ChangeResumeRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_resume_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeResumeRes.ProtoReflect.Descriptor instead.
func (*ChangeResumeRes) Descriptor() ([]byte, []int) {
	return file_proto_resume_proto_rawDescGZIP(), []int{6}
}

var File_proto_resume_proto protoreflect.FileDescriptor

var file_proto_resume_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x22, 0x1d, 0x0a, 0x05,
	0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x22, 0xee, 0x01, 0x0a, 0x0d,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62,
	0x6f, 0x75, 0x74, 0x4d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x62, 0x6f, 0x75,
	0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0x8a, 0x02, 0x0a,
	0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x64,
	0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x62, 0x6f, 0x75,
	0x74, 0x4d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62, 0x6f, 0x75, 0x74,
	0x4d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69,
	0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x62,
	0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x70,
	0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0xf0, 0x01, 0x0a, 0x0f, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1c, 0x0a,
	0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x62,
	0x6f, 0x75, 0x74, 0x4d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x62, 0x6f, 0x75,
	0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0x11, 0x0a, 0x0f,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x22,
	0x8c, 0x02, 0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x49, 0x64, 0x12,
	0x1c, 0x0a, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x62, 0x6f, 0x75, 0x74, 0x4d, 0x65, 0x12, 0x25, 0x0a, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x2e, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x52, 0x06, 0x73, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1c,
	0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x62,
	0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x61, 0x62, 0x6f, 0x75, 0x74, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73,
	0x12, 0x1c, 0x0a, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x6f, 0x6c, 0x69, 0x6f, 0x22, 0x11,
	0x0a, 0x0f, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65,
	0x73, 0x32, 0x97, 0x01, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x75, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x72,
	0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x12, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65,
	0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x1a, 0x17, 0x2e, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e,
	0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_resume_proto_rawDescOnce sync.Once
	file_proto_resume_proto_rawDescData = file_proto_resume_proto_rawDesc
)

func file_proto_resume_proto_rawDescGZIP() []byte {
	file_proto_resume_proto_rawDescOnce.Do(func() {
		file_proto_resume_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_resume_proto_rawDescData)
	})
	return file_proto_resume_proto_rawDescData
}

var file_proto_resume_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_resume_proto_goTypes = []any{
	(*Skill)(nil),           // 0: resume.Skill
	(*ResumeCreated)(nil),   // 1: resume.ResumeCreated
	(*ResumeChanged)(nil),   // 2: resume.ResumeChanged
	(*CreateResumeReq)(nil), // 3: resume.CreateResumeReq
	(*CreateResumeRes)(nil), // 4: resume.CreateResumeRes
	(*ChangeResumeReq)(nil), // 5: resume.ChangeResumeReq
	(*ChangeResumeRes)(nil), // 6: resume.ChangeResumeRes
}
var file_proto_resume_proto_depIdxs = []int32{
	0, // 0: resume.ResumeCreated.skills:type_name -> resume.Skill
	0, // 1: resume.ResumeChanged.skills:type_name -> resume.Skill
	0, // 2: resume.CreateResumeReq.skills:type_name -> resume.Skill
	0, // 3: resume.ChangeResumeReq.skills:type_name -> resume.Skill
	3, // 4: resume.ResumeService.CreateResume:input_type -> resume.CreateResumeReq
	5, // 5: resume.ResumeService.ChangeResume:input_type -> resume.ChangeResumeReq
	4, // 6: resume.ResumeService.CreateResume:output_type -> resume.CreateResumeRes
	6, // 7: resume.ResumeService.ChangeResume:output_type -> resume.ChangeResumeRes
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_resume_proto_init() }
func file_proto_resume_proto_init() {
	if File_proto_resume_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_resume_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_resume_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_resume_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ResumeChanged); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_resume_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateResumeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_resume_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*CreateResumeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_resume_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeResumeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_resume_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ChangeResumeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_resume_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_resume_proto_goTypes,
		DependencyIndexes: file_proto_resume_proto_depIdxs,
		MessageInfos:      file_proto_resume_proto_msgTypes,
	}.Build()
	File_proto_resume_proto = out.File
	file_proto_resume_proto_rawDesc = nil
	file_proto_resume_proto_goTypes = nil
	file_proto_resume_proto_depIdxs = nil
}
